name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
    - name: kekl
      run: |
        apt install -y neofetch
        neofetch
        
